spring.application.name=springboot-buildingblocks

spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:testdb


#This was added because on startup was getting error that the data.sql script is running before 
#the User entity gets created 
#https://www.baeldung.com/spring-boot-data-sql-and-schema-sql?utm_source=copilot.com
spring.jpa.defer-datasource-initialization=true
